language: python
python:
  - "2.6"
  - "2.7"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1"
# command to install dependencies
#not sure if this works
#install:
  #- pip install .
  #- pip install -r requirements.txt
# command to run tests

script: 
  - python builder/build.py
  - builder/packager.sh

